---
abstract: 'A form building, processing and data validation system based on Oogly!'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Oogly-Aagly
requires:
  Array::Unique: 0
  Cwd: 0
  Data::Dumper::Concise: 0
  File::Copy: 0
  File::ShareDir: 0
  Hash::Merge: 0
  Oogly: 0.31
  Template: 0
version: 0.04
